# __Programming Assignment 8__
### *__Q.1:- Write a Python Program to Add Two Matrices?__*
### __*Ans:-*__ 

In [7]:
import numpy as np

def addMatrices(a,b):

    arr1 = np.array(a)
    arr2 = np.array(b)

    out_arr = np.add(arr1, arr2)
    
    print ("1st Input array : ","\n", arr1)
    print ("2nd Input array : ","\n", arr2)
    print ("output added array : ","\n", out_arr)
    
addMatrices([[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]])
print("\n")
addMatrices([[2,3,5],[1,1,1],[2,2,2]],[[4,3,5],[1,2,3],[3,2,1]])

1st Input array :  
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2nd Input array :  
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
output added array :  
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


1st Input array :  
 [[2 3 5]
 [1 1 1]
 [2 2 2]]
2nd Input array :  
 [[4 3 5]
 [1 2 3]
 [3 2 1]]
output added array :  
 [[ 6  6 10]
 [ 2  3  4]
 [ 5  4  3]]


### *__Q.2:- Write a Python Program to Multiply Two Matrices?__*
### __*Ans:-*__ 

In [12]:
import numpy as np

def addMatrices(a,b):

    arr1 = np.array(a)
    arr2 = np.array(b)

    print ("1st Input array : ","\n", arr1)
    print ("2nd Input array : ","\n", arr2)

    if len(a[0]) == len(b):
        out_arr = np.dot(arr1, arr2)
        print ("output added array : ","\n", out_arr)
    
    else:
        print('Matrix Multiplication is Not Possible')
    
addMatrices([[1,2,3],[4,5,6],[7,8,9]],[[1,4,7],[2,5,8],[3,6,9]])
print("\n")
addMatrices([[2,3,5],[1,1,1],[2,2,2]],[[4,3,5],[1,2,3],[3,2,1]])


1st Input array :  
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2nd Input array :  
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
output added array :  
 [[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


1st Input array :  
 [[2 3 5]
 [1 1 1]
 [2 2 2]]
2nd Input array :  
 [[4 3 5]
 [1 2 3]
 [3 2 1]]
output added array :  
 [[26 22 24]
 [ 8  7  9]
 [16 14 18]]


### *__Q.3:- Write a Python Program to Transpose a Matrix?__*
### __*Ans:-*__ 

In [14]:
import numpy as np

def addMatrices(a):

    arr = np.array(a)

    print ("Input array : ","\n", arr)

    out_arr = np.transpose(arr)
    print ("output added array : ","\n", out_arr)
    
    
addMatrices([[1,2,3],[4,5,6],[7,8,9]])
print("\n")
addMatrices([[2,3,5],[1,1,1],[2,2,2]])


Input array :  
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
output added array :  
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


Input array :  
 [[2 3 5]
 [1 1 1]
 [2 2 2]]
output added array :  
 [[2 1 2]
 [3 1 2]
 [5 1 2]]


### *__Q.4:- Write a Python Program to Sort Words in Alphabetic Order?__*
### __*Ans:-*__ 

In [21]:
def sort_String():
    in_string = input("Enter a String: ").title()
    sorted_list = sorted(in_string.split(' '))
    print(' '.join(sorted_list))

sort_String()

Gagan Puneet Sachin Sanjib


### *__Q.5:- Write a Python Program to Remove Punctuation From a String?__*
### __*Ans:-*__ 

In [24]:
def remove_Pun():
    Pun = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    in_string = input('Enter a String: ')
    print(in_string)
    out_string = ''
    for i in in_string:
        if i not in Pun:
            out_string += i
    print(out_string)
    
remove_Pun()

p.n.sharma1049@gmail.com
pnsharma1049gmailcom


# __Assignment complete.__